version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports: 
      - "8888:80"
    environment:
     - ASPNETCORE_URLS=http://+:80
    depends_on:
     - sql

  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "numsey#2024"
    ports:
      - "1433:1433"
